"""add_sampling_workflow_fields

Revision ID: 45825a24e6a5
Revises: 4e3621754871
Create Date: 2026-03-05 11:23:45.416450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45825a24e6a5'
down_revision: Union[str, Sequence[str], None] = '4e3621754871'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=False, server_default='PENDING_REVIEW'))
        batch_op.add_column(sa.Column('reviewer_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('review_timestamp', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('submission_id', sa.String(length=36), nullable=True))
        batch_op.add_column(sa.Column('submission_timestamp', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_samplings_reviewer', 'usuario', ['reviewer_id'], ['usuario_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_samplings_reviewer', type_='foreignkey')
        batch_op.drop_column('submission_timestamp')
        batch_op.drop_column('submission_id')
        batch_op.drop_column('review_timestamp')
        batch_op.drop_column('reviewer_id')
        batch_op.drop_column('status')

    # ### end Alembic commands ###
