"""Add codigo to Area

Revision ID: 4a1e33009369
Revises: dd22f1dc7aa3
Create Date: 2026-03-09 14:52:29.692226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a1e33009369'
down_revision: Union[str, Sequence[str], None] = 'dd22f1dc7aa3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.add_column(sa.Column('codigo', sa.String(), nullable=True))
        batch_op.create_unique_constraint('uq_area_codigo', ['codigo'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.drop_constraint('uq_area_codigo', type_='unique')
        batch_op.drop_column('codigo')

    # ### end Alembic commands ###
