"""Add samplings table

Revision ID: 4e3621754871
Revises: 804ac0b9c491
Create Date: 2026-03-05 10:10:46.821213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e3621754871'
down_revision: Union[str, Sequence[str], None] = '804ac0b9c491'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('samplings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=True),
    sa.Column('start_datetime', sa.DateTime(), nullable=False),
    sa.Column('end_datetime', sa.DateTime(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('lot_id', sa.Integer(), nullable=True),
    sa.Column('sampling_point_id', sa.Integer(), nullable=True),
    sa.Column('extracted_quantity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('destination', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['inspector_id'], ['usuario.usuario_id'], ),
    sa.ForeignKeyConstraint(['lot_id'], ['orden_manufactura.orden_manufactura_id'], ),
    sa.ForeignKeyConstraint(['product_id'], ['producto.producto_id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['solicitud_muestreo.solicitud_muestreo_id'], ),
    sa.ForeignKeyConstraint(['sampling_point_id'], ['punto_muestreo.punto_muestreo_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('samplings')
    # ### end Alembic commands ###
