"""add batch_id to sampling

Revision ID: 5ee8bd9e5fda
Revises: b1125d37c434
Create Date: 2026-03-09 11:08:13.668360

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ee8bd9e5fda'
down_revision: Union[str, Sequence[str], None] = 'b1125d37c434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('batch_id', sa.String(length=36), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.drop_column('batch_id')

    # ### end Alembic commands ###
