"""add lot_number to sampling

Revision ID: 78278155d93b
Revises: 45825a24e6a5
Create Date: 2026-03-06 15:03:45.085502

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78278155d93b'
down_revision: Union[str, Sequence[str], None] = '45825a24e6a5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('lot_number', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.drop_column('lot_number')

    # ### end Alembic commands ###
