"""Add ad-hoc inspection fields

Revision ID: 7f41851bfe3f
Revises: c02ffb6ae86d
Create Date: 2026-03-09 08:52:18.058960

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f41851bfe3f'
down_revision: Union[str, Sequence[str], None] = 'c02ffb6ae86d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('sample_type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('equipo_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('operario_muestreado_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('region_swabbed', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_samplings_area', 'area', ['area_id'], ['area_id'])
        batch_op.create_foreign_key('fk_samplings_operario_muestreado', 'operario', ['operario_muestreado_id'], ['operario_id'])
        batch_op.create_foreign_key('fk_samplings_equipo', 'equipo_instrumento', ['equipo_id'], ['equipo_instrumento_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('samplings', schema=None) as batch_op:
        batch_op.drop_constraint('fk_samplings_equipo', type_='foreignkey')
        batch_op.drop_constraint('fk_samplings_operario_muestreado', type_='foreignkey')
        batch_op.drop_constraint('fk_samplings_area', type_='foreignkey')
        batch_op.drop_column('region_swabbed')
        batch_op.drop_column('area_id')
        batch_op.drop_column('operario_muestreado_id')
        batch_op.drop_column('equipo_id')
        batch_op.drop_column('sample_type')

    # ### end Alembic commands ###
