"""Add laboratories and role-based tracking

Revision ID: 7f9302674d44
Revises: dc8df4fa1307
Create Date: 2026-03-04 11:34:19.725236

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7f9302674d44'
down_revision: Union[str, Sequence[str], None] = 'dc8df4fa1307'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('laboratorio',
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('laboratorio_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario_laboratorio',
    sa.Column('usuario_laboratorio_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('laboratorio_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['laboratorio_id'], ['laboratorio.laboratorio_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('usuario_laboratorio_id')
    )
    op.create_table('solicitud_muestreo_equipo',
    sa.Column('solicitud_muestreo_equipo_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_muestreo_id', sa.Integer(), nullable=False),
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_instrumento_id'], ['equipo_instrumento.equipo_instrumento_id'], ),
    sa.ForeignKeyConstraint(['solicitud_muestreo_id'], ['solicitud_muestreo.solicitud_muestreo_id'], ),
    sa.PrimaryKeyConstraint('solicitud_muestreo_equipo_id')
    )
    op.create_table('uso_equipo_analisis',
    sa.Column('uso_equipo_analisis_id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=False),
    sa.Column('fecha_uso', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.analisis_id'], ),
    sa.ForeignKeyConstraint(['equipo_instrumento_id'], ['equipo_instrumento.equipo_instrumento_id'], ),
    sa.PrimaryKeyConstraint('uso_equipo_analisis_id')
    )
    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('planta_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('envio_muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino_deprecated', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('laboratorio_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_envio_muestra_laboratorio', 'laboratorio', ['laboratorio_id'], ['laboratorio_id'])
        batch_op.drop_column('destino')

    with op.batch_alter_table('planta', schema=None) as batch_op:
        batch_op.alter_column('sistema_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.add_column(sa.Column('laboratorio_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('justificacion', sa.Text(), nullable=True))
        batch_op.alter_column('recibido_en',
               existing_type=sa.VARCHAR(),
               nullable=True)
        batch_op.create_foreign_key('fk_recepcion_laboratorio', 'laboratorio', ['laboratorio_id'], ['laboratorio_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('recepcion', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('recibido_en',
               existing_type=sa.VARCHAR(),
               nullable=False)
        batch_op.drop_column('justificacion')
        batch_op.drop_column('laboratorio_id')

    with op.batch_alter_table('planta', schema=None) as batch_op:
        batch_op.alter_column('sistema_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    with op.batch_alter_table('envio_muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino', sa.VARCHAR(), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('laboratorio_id')
        batch_op.drop_column('destino_deprecated')

    with op.batch_alter_table('area', schema=None) as batch_op:
        batch_op.alter_column('planta_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    op.drop_table('uso_equipo_analisis')
    op.drop_table('solicitud_muestreo_equipo')
    op.drop_table('usuario_laboratorio')
    op.drop_table('laboratorio')
    # ### end Alembic commands ###
