"""add_inspector_fields

Revision ID: 804ac0b9c491
Revises: 7f9302674d44
Create Date: 2026-03-05 08:50:14.414057

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '804ac0b9c491'
down_revision: Union[str, Sequence[str], None] = '7f9302674d44'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('envio_muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('corroborado_por_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('fecha_corroboracion', sa.DateTime(), nullable=True))
        batch_op.create_foreign_key('fk_envio_muestra_corroborador', 'usuario', ['corroborado_por_id'], ['usuario_id'])
        batch_op.drop_column('destino_deprecated')

    with op.batch_alter_table('solicitud_muestreo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('fecha_limite', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_muestreo', schema=None) as batch_op:
        batch_op.drop_column('fecha_limite')

    with op.batch_alter_table('envio_muestra', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino_deprecated', sa.VARCHAR(), nullable=True))
        batch_op.drop_constraint('fk_envio_muestra_corroborador', type_='foreignkey')
        batch_op.drop_column('fecha_corroboracion')
        batch_op.drop_column('corroborado_por_id')

    # ### end Alembic commands ###
