"""Add granular fields to solicitud muestreo

Revision ID: b1125d37c434
Revises: 7f41851bfe3f
Create Date: 2026-03-09 09:03:11.805763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1125d37c434'
down_revision: Union[str, Sequence[str], None] = '7f41851bfe3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_muestreo', schema=None) as batch_op:
        batch_op.add_column(sa.Column('destino', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('producto_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('lote_number', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('cantidad_extraida', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('area_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('region_swabbed', sa.String(length=255), nullable=True))
        batch_op.create_foreign_key('fk_solicitud_muestreo_area', 'area', ['area_id'], ['area_id'])
        batch_op.create_foreign_key('fk_solicitud_muestreo_producto', 'producto', ['producto_id'], ['producto_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('solicitud_muestreo', schema=None) as batch_op:
        batch_op.drop_constraint('fk_solicitud_muestreo_producto', type_='foreignkey')
        batch_op.drop_constraint('fk_solicitud_muestreo_area', type_='foreignkey')
        batch_op.drop_column('region_swabbed')
        batch_op.drop_column('area_id')
        batch_op.drop_column('cantidad_extraida')
        batch_op.drop_column('lote_number')
        batch_op.drop_column('producto_id')
        batch_op.drop_column('destino')

    # ### end Alembic commands ###
