"""add_tipo_solicitud_muestreo_table

Revision ID: c02ffb6ae86d
Revises: 78278155d93b
Create Date: 2026-03-06 15:47:24.911017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c02ffb6ae86d'
down_revision: Union[str, Sequence[str], None] = '78278155d93b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tipo_solicitud_muestreo',
    sa.Column('tipo_solicitud_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('categoria', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_solicitud_id'),
    sa.UniqueConstraint('codigo')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tipo_solicitud_muestreo')
    # ### end Alembic commands ###
