"""initial_schema_v2

Revision ID: dc8df4fa1307
Revises: 
Create Date: 2026-02-26 09:36:28.790896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc8df4fa1307'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cepa_referencia',
    sa.Column('cepa_referencia_id', sa.Integer(), nullable=False),
    sa.Column('codigo_atcc', sa.String(), nullable=False),
    sa.Column('lote', sa.String(), nullable=True),
    sa.Column('pase', sa.Integer(), nullable=True),
    sa.Column('fecha_control', sa.Date(), nullable=True),
    sa.Column('estado_biologico', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('cepa_referencia_id'),
    sa.UniqueConstraint('codigo_atcc')
    )
    op.create_table('estado_analisis',
    sa.Column('estado_analisis_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('estado_analisis_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_equipo',
    sa.Column('estado_equipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('estado_equipo_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_manufactura',
    sa.Column('estado_manufactura_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('estado_manufactura_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_qc',
    sa.Column('estado_qc_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('estado_qc_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('estado_solicitud',
    sa.Column('estado_solicitud_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('estado_solicitud_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('medio_preparado',
    sa.Column('medio_preparado_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('medio_preparado_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('metodo_version',
    sa.Column('metodo_version_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=True),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('metodo_version_id')
    )
    op.create_table('polvo_suplemento',
    sa.Column('polvo_suplemento_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('polvo_suplemento_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('rol',
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('rol_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('sistema',
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('sistema_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('tipo_equipo',
    sa.Column('tipo_equipo_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('tipo_equipo_id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuario',
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=True),
    sa.Column('firma', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('usuario_id')
    )
    op.create_table('audit_trail',
    sa.Column('audit_trail_id', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(), nullable=False),
    sa.Column('registro_id', sa.BigInteger(), nullable=False),
    sa.Column('columna', sa.String(), nullable=True),
    sa.Column('old_val', sa.Text(), nullable=True),
    sa.Column('new_val', sa.Text(), nullable=True),
    sa.Column('accion', sa.String(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('audit_trail_id')
    )
    op.create_table('operario',
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('apellido', sa.String(), nullable=False),
    sa.Column('codigo_empleado', sa.String(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('operario_id'),
    sa.UniqueConstraint('codigo_empleado')
    )
    op.create_table('planta',
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistema.sistema_id'], ),
    sa.PrimaryKeyConstraint('planta_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('recepcion_polvo_suplemento',
    sa.Column('recepcion_polvo_suplemento_id', sa.Integer(), nullable=False),
    sa.Column('polvo_suplemento_id', sa.Integer(), nullable=False),
    sa.Column('lote_proveedor', sa.String(), nullable=False),
    sa.Column('vence', sa.Date(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['polvo_suplemento_id'], ['polvo_suplemento.polvo_suplemento_id'], ),
    sa.PrimaryKeyConstraint('recepcion_polvo_suplemento_id')
    )
    op.create_table('revision',
    sa.Column('revision_id', sa.Integer(), nullable=False),
    sa.Column('tabla', sa.String(), nullable=False),
    sa.Column('registro_id', sa.BigInteger(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('conclusion', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('revision_id')
    )
    op.create_table('usuario_rol',
    sa.Column('usuario_rol_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('rol_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['rol_id'], ['rol.rol_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('usuario_rol_id')
    )
    op.create_table('area',
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['planta.planta_id'], ),
    sa.PrimaryKeyConstraint('area_id')
    )
    op.create_table('orden_preparacion_medio',
    sa.Column('orden_preparacion_medio_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('medio_preparado_id', sa.Integer(), nullable=False),
    sa.Column('lote', sa.String(), nullable=False),
    sa.Column('volumen_total', sa.Float(), nullable=False),
    sa.Column('unidad_volumen', sa.String(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['medio_preparado_id'], ['medio_preparado.medio_preparado_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.PrimaryKeyConstraint('orden_preparacion_medio_id')
    )
    op.create_table('producto',
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('planta_id', sa.Integer(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['planta_id'], ['planta.planta_id'], ),
    sa.PrimaryKeyConstraint('producto_id'),
    sa.UniqueConstraint('codigo', name='uq_producto_codigo'),
    sa.UniqueConstraint('nombre', name='uq_producto_nombre')
    )
    op.create_table('stock_polvo_suplemento',
    sa.Column('stock_polvo_suplemento_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_polvo_suplemento_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['recepcion_polvo_suplemento_id'], ['recepcion_polvo_suplemento.recepcion_polvo_suplemento_id'], ),
    sa.PrimaryKeyConstraint('stock_polvo_suplemento_id')
    )
    op.create_table('equipo_instrumento',
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('tipo_equipo_id', sa.Integer(), nullable=False),
    sa.Column('estado_equipo_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.ForeignKeyConstraint(['estado_equipo_id'], ['estado_equipo.estado_equipo_id'], ),
    sa.ForeignKeyConstraint(['tipo_equipo_id'], ['tipo_equipo.tipo_equipo_id'], ),
    sa.PrimaryKeyConstraint('equipo_instrumento_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('especificacion',
    sa.Column('especificacion_id', sa.Integer(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('parametro', sa.String(), nullable=False),
    sa.Column('tipo_limite', sa.String(), nullable=False),
    sa.Column('valor_min', sa.Float(), nullable=True),
    sa.Column('valor_max', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.producto_id'], ),
    sa.PrimaryKeyConstraint('especificacion_id')
    )
    op.create_table('orden_manufactura',
    sa.Column('orden_manufactura_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('lote', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('producto_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.ForeignKeyConstraint(['producto_id'], ['producto.producto_id'], ),
    sa.PrimaryKeyConstraint('orden_manufactura_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('punto_muestreo',
    sa.Column('punto_muestreo_id', sa.Integer(), nullable=False),
    sa.Column('codigo', sa.String(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('sistema_id', sa.Integer(), nullable=True),
    sa.Column('area_id', sa.Integer(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.ForeignKeyConstraint(['sistema_id'], ['sistema.sistema_id'], ),
    sa.PrimaryKeyConstraint('punto_muestreo_id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('stock_medios',
    sa.Column('stock_medios_id', sa.Integer(), nullable=False),
    sa.Column('orden_preparacion_medio_id', sa.Integer(), nullable=False),
    sa.Column('lote_interno', sa.String(), nullable=False),
    sa.Column('vence', sa.Date(), nullable=False),
    sa.Column('estado_qc_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['estado_qc_id'], ['estado_qc.estado_qc_id'], ),
    sa.ForeignKeyConstraint(['orden_preparacion_medio_id'], ['orden_preparacion_medio.orden_preparacion_medio_id'], ),
    sa.PrimaryKeyConstraint('stock_medios_id')
    )
    op.create_table('uso_polvo_suplemento',
    sa.Column('uso_polvo_suplemento_id', sa.Integer(), nullable=False),
    sa.Column('stock_polvo_suplemento_id', sa.Integer(), nullable=False),
    sa.Column('orden_preparacion_medio_id', sa.Integer(), nullable=False),
    sa.Column('cantidad', sa.Float(), nullable=False),
    sa.Column('unidad', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['orden_preparacion_medio_id'], ['orden_preparacion_medio.orden_preparacion_medio_id'], ),
    sa.ForeignKeyConstraint(['stock_polvo_suplemento_id'], ['stock_polvo_suplemento.stock_polvo_suplemento_id'], ),
    sa.PrimaryKeyConstraint('uso_polvo_suplemento_id')
    )
    op.create_table('aprobacion_medios',
    sa.Column('aprobacion_medios_id', sa.Integer(), nullable=False),
    sa.Column('stock_medios_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.ForeignKeyConstraint(['stock_medios_id'], ['stock_medios.stock_medios_id'], ),
    sa.PrimaryKeyConstraint('aprobacion_medios_id')
    )
    op.create_table('calibracion_calificacion_equipo',
    sa.Column('calibracion_calificacion_equipo_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('vence', sa.Date(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_instrumento_id'], ['equipo_instrumento.equipo_instrumento_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.PrimaryKeyConstraint('calibracion_calificacion_equipo_id')
    )
    op.create_table('historico_estado_equipo',
    sa.Column('historico_estado_equipo_id', sa.Integer(), nullable=False),
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=False),
    sa.Column('estado_equipo_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_instrumento_id'], ['equipo_instrumento.equipo_instrumento_id'], ),
    sa.ForeignKeyConstraint(['estado_equipo_id'], ['estado_equipo.estado_equipo_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('historico_estado_equipo_id')
    )
    op.create_table('manufactura',
    sa.Column('manufactura_id', sa.Integer(), nullable=False),
    sa.Column('orden_manufactura_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('estado_manufactura_id', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estado_manufactura_id'], ['estado_manufactura.estado_manufactura_id'], ),
    sa.ForeignKeyConstraint(['orden_manufactura_id'], ['orden_manufactura.orden_manufactura_id'], ),
    sa.PrimaryKeyConstraint('manufactura_id')
    )
    op.create_table('solicitud_muestreo',
    sa.Column('solicitud_muestreo_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('orden_manufactura_id', sa.Integer(), nullable=True),
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=True),
    sa.Column('punto_muestreo_id', sa.Integer(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=True),
    sa.Column('estado_solicitud_id', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['equipo_instrumento_id'], ['equipo_instrumento.equipo_instrumento_id'], ),
    sa.ForeignKeyConstraint(['estado_solicitud_id'], ['estado_solicitud.estado_solicitud_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.ForeignKeyConstraint(['orden_manufactura_id'], ['orden_manufactura.orden_manufactura_id'], ),
    sa.ForeignKeyConstraint(['punto_muestreo_id'], ['punto_muestreo.punto_muestreo_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('solicitud_muestreo_id')
    )
    op.create_table('zona_equipo',
    sa.Column('zona_equipo_id', sa.Integer(), nullable=False),
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['equipo_instrumento_id'], ['equipo_instrumento.equipo_instrumento_id'], ),
    sa.PrimaryKeyConstraint('zona_equipo_id')
    )
    op.create_table('historico_estado_manufactura',
    sa.Column('historico_estado_manufactura_id', sa.Integer(), nullable=False),
    sa.Column('manufactura_id', sa.Integer(), nullable=False),
    sa.Column('estado_manufactura_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['estado_manufactura_id'], ['estado_manufactura.estado_manufactura_id'], ),
    sa.ForeignKeyConstraint(['manufactura_id'], ['manufactura.manufactura_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('historico_estado_manufactura_id')
    )
    op.create_table('historico_solicitud_muestreo',
    sa.Column('historico_solicitud_muestreo_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_muestreo_id', sa.Integer(), nullable=False),
    sa.Column('estado_solicitud_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['estado_solicitud_id'], ['estado_solicitud.estado_solicitud_id'], ),
    sa.ForeignKeyConstraint(['solicitud_muestreo_id'], ['solicitud_muestreo.solicitud_muestreo_id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuario.usuario_id'], ),
    sa.PrimaryKeyConstraint('historico_solicitud_muestreo_id')
    )
    op.create_table('manufactura_operario',
    sa.Column('manufactura_operario_id', sa.Integer(), nullable=False),
    sa.Column('manufactura_id', sa.Integer(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.Column('entrada', sa.DateTime(), nullable=True),
    sa.Column('salida', sa.DateTime(), nullable=True),
    sa.Column('rol_operacion', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['manufactura_id'], ['manufactura.manufactura_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.PrimaryKeyConstraint('manufactura_operario_id')
    )
    op.create_table('muestreo',
    sa.Column('muestreo_id', sa.Integer(), nullable=False),
    sa.Column('solicitud_muestreo_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('fecha_fin', sa.DateTime(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.ForeignKeyConstraint(['solicitud_muestreo_id'], ['solicitud_muestreo.solicitud_muestreo_id'], ),
    sa.PrimaryKeyConstraint('muestreo_id')
    )
    op.create_table('muestra',
    sa.Column('muestra_id', sa.Integer(), nullable=False),
    sa.Column('muestreo_id', sa.Integer(), nullable=False),
    sa.Column('punto_muestreo_id', sa.Integer(), nullable=True),
    sa.Column('zona_equipo_id', sa.Integer(), nullable=True),
    sa.Column('operario_muestreado_id', sa.Integer(), nullable=True),
    sa.Column('tipo_muestra', sa.String(), nullable=False),
    sa.Column('codigo_etiqueta', sa.String(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['muestreo_id'], ['muestreo.muestreo_id'], ),
    sa.ForeignKeyConstraint(['operario_muestreado_id'], ['operario.operario_id'], ),
    sa.ForeignKeyConstraint(['punto_muestreo_id'], ['punto_muestreo.punto_muestreo_id'], ),
    sa.ForeignKeyConstraint(['zona_equipo_id'], ['zona_equipo.zona_equipo_id'], ),
    sa.PrimaryKeyConstraint('muestra_id'),
    sa.UniqueConstraint('codigo_etiqueta')
    )
    op.create_table('envio_muestra',
    sa.Column('envio_muestra_id', sa.Integer(), nullable=False),
    sa.Column('muestra_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.Column('destino', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['muestra_id'], ['muestra.muestra_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.PrimaryKeyConstraint('envio_muestra_id')
    )
    op.create_table('recepcion',
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('envio_muestra_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.Column('recibido_en', sa.String(), nullable=False),
    sa.Column('decision', sa.String(), nullable=False),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['envio_muestra_id'], ['envio_muestra.envio_muestra_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.PrimaryKeyConstraint('recepcion_id')
    )
    op.create_table('analisis',
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('muestra_id', sa.Integer(), nullable=False),
    sa.Column('recepcion_id', sa.Integer(), nullable=False),
    sa.Column('metodo_version_id', sa.Integer(), nullable=False),
    sa.Column('especificacion_id', sa.Integer(), nullable=True),
    sa.Column('estado_analisis_id', sa.Integer(), nullable=False),
    sa.Column('fecha_inicio', sa.DateTime(), nullable=True),
    sa.Column('ultimo_cambio', sa.DateTime(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['especificacion_id'], ['especificacion.especificacion_id'], ),
    sa.ForeignKeyConstraint(['estado_analisis_id'], ['estado_analisis.estado_analisis_id'], ),
    sa.ForeignKeyConstraint(['metodo_version_id'], ['metodo_version.metodo_version_id'], ),
    sa.ForeignKeyConstraint(['muestra_id'], ['muestra.muestra_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.ForeignKeyConstraint(['recepcion_id'], ['recepcion.recepcion_id'], ),
    sa.PrimaryKeyConstraint('analisis_id')
    )
    op.create_table('historial_estado_analisis',
    sa.Column('historial_estado_analisis_id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('estado_analisis_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(), nullable=False),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.analisis_id'], ),
    sa.ForeignKeyConstraint(['estado_analisis_id'], ['estado_analisis.estado_analisis_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.PrimaryKeyConstraint('historial_estado_analisis_id')
    )
    op.create_table('incubacion',
    sa.Column('incubacion_id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('equipo_instrumento_id', sa.Integer(), nullable=False),
    sa.Column('entrada', sa.DateTime(), nullable=True),
    sa.Column('salida', sa.DateTime(), nullable=True),
    sa.Column('temp_registrada', sa.Float(), nullable=True),
    sa.Column('unidad_temp', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.analisis_id'], ),
    sa.ForeignKeyConstraint(['equipo_instrumento_id'], ['equipo_instrumento.equipo_instrumento_id'], ),
    sa.PrimaryKeyConstraint('incubacion_id')
    )
    op.create_table('resultado',
    sa.Column('resultado_id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('fecha_reporte', sa.DateTime(), nullable=True),
    sa.Column('operario_id', sa.Integer(), nullable=False),
    sa.Column('valor', sa.String(), nullable=True),
    sa.Column('valor_numerico', sa.Float(), nullable=True),
    sa.Column('unidad', sa.String(), nullable=True),
    sa.Column('conforme', sa.Boolean(), nullable=True),
    sa.Column('observacion', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.analisis_id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operario.operario_id'], ),
    sa.PrimaryKeyConstraint('resultado_id')
    )
    op.create_table('uso_cepa',
    sa.Column('uso_cepa_id', sa.Integer(), nullable=False),
    sa.Column('cepa_referencia_id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.analisis_id'], ),
    sa.ForeignKeyConstraint(['cepa_referencia_id'], ['cepa_referencia.cepa_referencia_id'], ),
    sa.PrimaryKeyConstraint('uso_cepa_id')
    )
    op.create_table('uso_medios',
    sa.Column('uso_medios_id', sa.Integer(), nullable=False),
    sa.Column('analisis_id', sa.Integer(), nullable=False),
    sa.Column('stock_medios_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['analisis_id'], ['analisis.analisis_id'], ),
    sa.ForeignKeyConstraint(['stock_medios_id'], ['stock_medios.stock_medios_id'], ),
    sa.PrimaryKeyConstraint('uso_medios_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('uso_medios')
    op.drop_table('uso_cepa')
    op.drop_table('resultado')
    op.drop_table('incubacion')
    op.drop_table('historial_estado_analisis')
    op.drop_table('analisis')
    op.drop_table('recepcion')
    op.drop_table('envio_muestra')
    op.drop_table('muestra')
    op.drop_table('muestreo')
    op.drop_table('manufactura_operario')
    op.drop_table('historico_solicitud_muestreo')
    op.drop_table('historico_estado_manufactura')
    op.drop_table('zona_equipo')
    op.drop_table('solicitud_muestreo')
    op.drop_table('manufactura')
    op.drop_table('historico_estado_equipo')
    op.drop_table('calibracion_calificacion_equipo')
    op.drop_table('aprobacion_medios')
    op.drop_table('uso_polvo_suplemento')
    op.drop_table('stock_medios')
    op.drop_table('punto_muestreo')
    op.drop_table('orden_manufactura')
    op.drop_table('especificacion')
    op.drop_table('equipo_instrumento')
    op.drop_table('stock_polvo_suplemento')
    op.drop_table('producto')
    op.drop_table('orden_preparacion_medio')
    op.drop_table('area')
    op.drop_table('usuario_rol')
    op.drop_table('revision')
    op.drop_table('recepcion_polvo_suplemento')
    op.drop_table('planta')
    op.drop_table('operario')
    op.drop_table('audit_trail')
    op.drop_table('usuario')
    op.drop_table('tipo_equipo')
    op.drop_table('sistema')
    op.drop_table('rol')
    op.drop_table('polvo_suplemento')
    op.drop_table('metodo_version')
    op.drop_table('medio_preparado')
    op.drop_table('estado_solicitud')
    op.drop_table('estado_qc')
    op.drop_table('estado_manufactura')
    op.drop_table('estado_equipo')
    op.drop_table('estado_analisis')
    op.drop_table('cepa_referencia')
    # ### end Alembic commands ###
