"""Add ZonaArea table

Revision ID: dd22f1dc7aa3
Revises: 5ee8bd9e5fda
Create Date: 2026-03-09 14:42:02.097691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dd22f1dc7aa3'
down_revision: Union[str, Sequence[str], None] = '5ee8bd9e5fda'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('zona_area',
    sa.Column('zona_area_id', sa.Integer(), nullable=False),
    sa.Column('area_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['area_id'], ['area.area_id'], ),
    sa.PrimaryKeyConstraint('zona_area_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('zona_area')
    # ### end Alembic commands ###
